Update octal literal to hex
Strict mode in later versions of node caused programs that use this to crash due to the octal literal with

```
diffie-hellman-explained/node_modules/cli-clear/index.js:26
	stdout += "\033[0f";
	            ^^
SyntaxError: Octal literals are not allowed in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/a2sl1zz/git/diffie-hellman-explained/tutorial.js:2:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

This converts it to hex.